name: knightfoxapps
favicon: null
layout_spectrum: 0.5964887335430831
typography_spectrum: 0.5083479406312108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1829535043798387
  lightness: 0.23974177171476185
  saturation: 0.6525664429645985
  rhythmicContrast: 0.24771124962717295
purpose: []
